/* export const GET_DEMO_REQUEST = 'GET_DEMO_REQUEST';
export const GET_DEMO_SUCCESS = 'GET_DEMO_SUCCESS';
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR'; */

export const SEARCH_MOVIES_REQUEST = "SEARCH_MOVIES_REQUEST";
export const SEARCH_MOVIES_SUCCESS = "SEARCH_MOVIES_SUCCESS";
export const SEARCH_MOVIES_ERROR = "SEARCH_MOVIES_ERROR";

export const SEARCH_MOVIE_BY_ID_REQUEST = "SEARCH_MOVIE_BY_ID_REQUEST";
export const SEARCH_MOVIE_BY_ID_SUCCESS = "SEARCH_MOVIE_BY_ID_SUCCESS";
export const SEARCH_MOVIE_BY_ID_ERROR = "SEARCH_MOVIE_BY_ID_ERROR";
